### ISSUE TITLE
Why the :call search funtion not work in my ideavim（IntelliJ IDEA 2024.2.3））

### ISSUE THREAD

**Issue by liango2** [magidc/dotfiles#1]
please help me take a look 
Why the :call search funtion not work in my ideavim（IntelliJ IDEA 2024.2.3））
How does the search method work

"--  Class motions
nnoremap [c :call search('\<class\>', 'bW')<cr> ^ 
nnoremap ]c :call search('\<class\>', 'W')<cr> ^ 
nnoremap [C :call search('\<class\>', 'bW')<cr> f{% 
nnoremap ]C :call search('\<class\>', 'W')<cr> f{%

**Comment by magidc** [comment]
You are right, it doesn't work for me either. As I don't often use those shortcuts so I hadn't realized they no longer work. I prefer to use `space c x` (if you use my config) as it opens a popup menu where I can quickly navigate to any class or method of the file. Anyway I have updated the class motions mappings to make them work:

```vimscript
"--  Class motions
if &ide =~? 'intellij idea'
  "--- Previous class opening
  nnoremap [c 0?\<class\> <cr>f{:nohlsearch<cr>  
  "--- Next class opening
  nnoremap ]c $/\<class\> <cr>f{:nohlsearch<cr>
  "--- Previous class closing
  nnoremap [C $?\<class\> <cr>nf{%:nohlsearch<cr>
  "--- Next class closing
  nnoremap ]C 0/\<class\> <cr>f{%:nohlsearch<cr>
endif

``` 
They include some tweaks to achieve the desirable motion no matter where your cursor is. As the search function is used, they also include command `nohlsearch` to avoid that the  word "class" remains highlighted. Lastly, I have put these commands inside an "if" clause in order to enable them just when you are using Intellij and therefore Java. As the same config applies to other Jetbrains IDEs for other languages, it wouldn't work for all of them cause not all use the keyword "class" (i.e. Python)

**Comment by liango2** [comment]
Thank you for configuring it. It's very convenient to use and I feel like the coding speed has increased
![AF9CF8AB6AC99B35118C7441E27B77B4](https://github.com/user-attachments/assets/ddef4a4a-4fef-4a8b-bb3c-3b6120d17635)

**Comment by magidc** [comment]
I am glad to know you find it useful. I have updated my previous post as the comments about the commands where missplaced
